### ISSUE TITLE
Render fail when Grafana is running at a path prefix

### ISSUE THREAD

**Issue by duchieu2k** [mahendrapaipuri/grafana-dashboard-reporter-app#358]
My k8s cluster has ingress nginx and grafana, my Grafana deployment is defined as below:

```
containers:      
- env:        
        - name: GF_DATABASE_TYPE
          value: mysql
        - name: GF_DATABASE_HOST
           value: mariadb
        - name: GF_DATABASE_PORT
          value: "3306"
        - name: GF_DATABASE_NAME
          value: nmaa_grafana
        - name: GF_DATABASE_USER
           value: grafana
        - name: GF_DATABASE_PASSWORD
          value: <redacted>
        - name: GF_SECURITY_ADMIN_USER
          value: <redacted>
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: <redacted>
        - name: TZ
          value: Asia/Ho_Chi_Minh
        - name: GF_SECURITY_ANGULAR_SUPPORT_ENABLED
          value: "true"
        - name: GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS
          value: icinga2-report-datasource,icinga2-report-panel,icinga2-report-panel-transposed,mahendrapaipuri-dashboardreporter-app
        - name: GF_SERVER_ROOT_URL
          value: https://10.98.100.193/grafana
        - name: GF_LOG_FILTERS
          value: rendering:debug plugin.mahendrapaipuri-dashboardreporter-app:debug
        - name: GF_FEATURE_TOGGLES_ENABLE
          value: accessControlOnCall,idForwarding
        - name: GF_REPORTER_PLUGIN_APP_URL
          value: https://10.98.100.193/grafana/
        - name: GF_RENDERING_SERVER_URL
          value: http://renderer:8081/render
        - name: GF_REPORTER_PLUGIN_REMOTE_CHROME_URL
          value: http://chrome:9222
        - name: GF_RENDERING_CALLBACK_URL
          value: https://10.98.100.193/grafana/
        - name: GF_REPORTER_PLUGIN_SKIP_TLS_CHECK
          value: "true"
        - name: GF_REPORTER_PLUGIN_NATIVE_RENDERER
          value: "false"
        image: grafana:renderer
        imagePullPolicy: Always
        name: grafana
        ports:
        - containerPort: 3000
          name: grafana
          protocol: TCP
      - args:
        - --ignore-certificate-errors
        image: chromedp/headless-shell:latest
        imagePullPolicy: IfNotPresent
        name: chrome
        ports:
        - containerPort: 9222
          protocol: TCP
      - env:
        - name: IGNORE_HTTPS_ERRORS
          value: "true"
        - name: RENDERING_MODE
          value: clustered
        - name: RENDERING_CLUSTERING_MODE
          value: context
        - name: RENDERING_CLUSTERING_MAX_CONCURRENCY
          value: "5"
        - name: RENDERING_CLUSTERING_TIMEOUT
          value: "60"
        image: grafana/grafana-image-renderer:latest
        imagePullPolicy: IfNotPresent
        name: renderer
        ports:
        - containerPort: 8081
          name: renderer
          protocol: TCP
```

my dockerfile
```
FROM docker.io/grafana/grafana:11.6.1-ubuntu

LABEL org.opencontainers.image.authors="svtech"
LABEL org.opencontainers.image.source=https://github.com/svtechnmaa/stacked_charts

ENV GDG_VERSION=0.7.2

USER root

RUN apt-get update -y \
 && apt-get -qq --no-install-recommends -y install wget jq \
 && cd /tmp \
 && wget https://github.com/esnet/gdg/releases/download/v${GDG_VERSION}/gdg_${GDG_VERSION}_amd64.deb \
 && dpkg -i gdg_${GDG_VERSION}_amd64.deb \
 && rm -rf gdg_${GDG_VERSION}_amd64.deb \
 && apt-get clean all \
 && rm -rf /var/cache/apt/archives /var/lib/apt/lists/*

RUN mkdir -p /opt/grafana-entities/dashboards \
 && mkdir -p /opt/grafana-entities/datasources \
 && mkdir /tmp/grafana-entities

COPY ./configs/plugins /var/lib/grafana/plugins
COPY ./configs/scripted_dashboards/service_detail_dashboard.js /usr/share/grafana/public/dashboards/service_detail_dashboard.js

COPY ./configs/grafana.ini /etc/grafana/grafana.ini
COPY ./configs/grafana-entities /tmp/grafana-entities

RUN cp -rf /tmp/grafana-entities/conf /opt/grafana-entities \
 && cp -rf /tmp/grafana-entities/dashboards /opt/grafana-entities \
 && rm -rf /tmp/grafana-entities

RUN grafana-cli --pluginUrl "https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/releases/download/v1.7.7/mahendrapaipuri-dashboardreporter-app-1.7.7.zip" plugins install mahendrapaipuri-dashboardreporter-app \
 && grafana-cli plugins install sni-thruk-datasource \
 && grafana-cli plugins install yesoreyeram-infinity-datasource \
 && grafana-cli plugins install grafana-clickhouse-datasource \
 && grafana-cli plugins install grafana-image-renderer

COPY ./run.sh /run.sh

ENTRYPOINT [ "/run.sh" ]
```

Grafana is running at root url `https://10.98.100.193/grafana`, i set `GF_REPORTER_PLUGIN_APP_URL=https://10.98.100.193/grafana`
But when rendering report, it always return `https://10.98.100.193/render` instead of `https://10.98.100.193/grafana/render` and its logs like this

```
logger=plugin.mahendrapaipuri-dashboardreporter-app t=2025-06-20T15:57:36.172724982+07:00 level=debug msg="Plugin Request Started" endpoint=callResource pluginId=mahendrapaipuri-dashboardreporter-app
logger=plugin.mahendrapaipuri-dashboardreporter-app t=2025-06-20T15:57:36.172933585+07:00 level=info msg="generate report using config: Theme: light; Orientation: landscape; Layout: grid; Dashboard Mode: default; Time Zone: Asia/Saigon; Time Format: Mon Jan _2 15:04:05 MST 2006; Encoded Logo: ; Max Renderer Workers: 2; Max Browser Workers: 2; Remote Chrome Addr: http://chrome:9222; App URL: https://10.98.100.193/grafana/; TLS Skip verify: true; Included Panel IDs: all; Excluded Panel IDs: none Included Data for Panel IDs: none; Native Renderer: false; Client Timeout: 30" dash_uid=icinga2-default endpoint=callResource pluginId=mahendrapaipuri-dashboardreporter-app user=thrukadmin
logger=plugin.mahendrapaipuri-dashboardreporter-app t=2025-06-20T15:57:36.173011394+07:00 level=debug msg="using user configured token" dash_uid=icinga2-default endpoint=callResource pluginId=mahendrapaipuri-dashboardreporter-app user=thrukadmin
logger=plugin.mahendrapaipuri-dashboardreporter-app t=2025-06-20T15:57:36.201755961+07:00 level=debug msg="token unchanged returning existing authz client" endpoint=callResource pluginId=mahendrapaipuri-dashboardreporter-app
logger=plugin.mahendrapaipuri-dashboardreporter-app t=2025-06-20T15:57:36.221256801+07:00 level=info msg="generate report using remote chrome" dash_uid=icinga2-default endpoint=callResource pluginId=mahendrapaipuri-dashboardreporter-app user=thrukadmin
logger=plugin.mahendrapaipuri-dashboardreporter-app t=2025-06-20T15:57:36.379071243+07:00 level=error msg="unhandled page event %T" dash_uid=icinga2-default endpoint=callResource user=thrukadmin pluginId=mahendrapaipuri-dashboardreporter-app subsystem=chromium EXTRA_VALUE_AT_END="map[frameId:8CF454A72132C1C5D5AD43E01E00EECF loaderId:33B077D4D842270ACBCF5FE70D1824F5 navigationType:differentDocument url:https://10.98.100.193/grafana/d/icinga2-default/_?dashUid=icinga2-default&from=now-6h&timezone=Asia%2FSaigon&to=now&var-command=ping4&var-hostname=MX480_03-VIETTEL-AGG01-RE0&var-perf=pl&var-service=ping4&var-unit=percent]"
logger=plugin.mahendrapaipuri-dashboardreporter-app t=2025-06-20T15:57:37.400455999+07:00 level=error msg="unhandled page event %T" EXTRA_VALUE_AT_END="map[frameId:937CE2E0678A0D23F65FB5FC94C38089 loaderId:C70446DB0629527206A6C2D0AF208945 navigationType:differentDocument url:about:srcdoc]" dash_uid=icinga2-default endpoint=callResource subsystem=chromium user=thrukadmin pluginId=mahendrapaipuri-dashboardreporter-app
logger=context userId=0 orgId=1 uname= t=2025-06-20T15:57:37.500650601+07:00 level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=10.98.100.192 time_ms=4 duration=4.327216ms size=0 referer= handler=/api/live/ws status_source=server
logger=plugin.mahendrapaipuri-dashboardreporter-app t=2025-06-20T15:57:39.361146325+07:00 level=debug msg="fetch dashboard panels metadata" user=thrukadmin duration=3.139665165s pluginId=mahendrapaipuri-dashboardreporter-app url="https://10.98.100.193/grafana/d/icinga2-default/_?dashUid=icinga2-default&from=now-6h&timezone=Asia%2FSaigon&to=now&var-command=ping4&var-hostname=MX480_03-VIETTEL-AGG01-RE0&var-perf=pl&var-service=ping4&var-unit=percent" dash_uid=icinga2-default endpoint=callResource
logger=plugin.mahendrapaipuri-dashboardreporter-app t=2025-06-20T15:57:39.361221485+07:00 level=debug msg="dashboard data fetch from browser" dash_uid=icinga2-default endpoint=callResource num_panels=1 user=thrukadmin data="[map[height:372 id:panel-1 title:ping4 width:1920 x:16 y:144]]" pluginId=mahendrapaipuri-dashboardreporter-app
logger=plugin.mahendrapaipuri-dashboardreporter-app t=2025-06-20T15:57:39.361262116+07:00 level=debug msg="fetched panels" panels="Panel ID: panel-1 and Title: ping4" pluginId=mahendrapaipuri-dashboardreporter-app user=thrukadmin dash_uid=icinga2-default endpoint=callResource
logger=plugin.mahendrapaipuri-dashboardreporter-app t=2025-06-20T15:57:39.361298996+07:00 level=debug msg="dashboard data" user=thrukadmin dash_uid=icinga2-default duration=3.139837243s endpoint=callResource pluginId=mahendrapaipuri-dashboardreporter-app
logger=plugin.mahendrapaipuri-dashboardreporter-app t=2025-06-20T15:58:09.3838083+07:00 level=debug msg="fetch panel PNG" endpoint=callResource renderer=grafana-image-renderer user=thrukadmin dash_uid=icinga2-default duration=30.02249111s panel_id=panel-1 pluginId=mahendrapaipuri-dashboardreporter-app url="https://10.98.100.193/render/d-solo/icinga2-default/_?dashUid=icinga2-default&from=now-6h&height=360&panelId=panel-1&theme=light&timezone=Asia%2FSaigon&to=now&var-command=ping4&var-hostname=MX480_03-VIETTEL-AGG01-RE0&var-perf=pl&var-service=ping4&var-unit=percent&width=1536"
logger=plugin.mahendrapaipuri-dashboardreporter-app t=2025-06-20T15:58:09.383864969+07:00 level=debug msg="panel PNGs and/or data generation" duration=30.022619635s endpoint=callResource pluginId=mahendrapaipuri-dashboardreporter-app user=thrukadmin dash_uid=icinga2-default
logger=plugin.mahendrapaipuri-dashboardreporter-app t=2025-06-20T15:58:09.38389549+07:00 level=debug msg="report generation" duration=33.162481738s endpoint=callResource pluginId=mahendrapaipuri-dashboardreporter-app user=thrukadmin dash_uid=icinga2-default
logger=plugin.mahendrapaipuri-dashboardreporter-app t=2025-06-20T15:58:09.383925337+07:00 level=error msg="error generating report" dash_uid=icinga2-default endpoint=callResource err="failed to populate panels: failed to generate report: failed to fetch PNG data for panel panel-1: dashboard request does not return 200 OK: URL: https://10.98.100.193/render/d-solo/icinga2-default/_?dashUid=icinga2-default&from=now-6h&height=360&panelId=panel-1&theme=light&timezone=Asia%2FSaigon&to=now&var-command=ping4&var-hostname=MX480_03-VIETTEL-AGG01-RE0&var-perf=pl&var-service=ping4&var-unit=percent&width=1536. Status: 404 Not Found, message: <html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n" pluginId=mahendrapaipuri-dashboardreporter-app user=thrukadmin
logger=plugin.mahendrapaipuri-dashboardreporter-app t=2025-06-20T15:58:09.383942633+07:00 level=info msg="Plugin Request Completed" statusSource=plugin duration=33.211143006s endpoint=callResource pluginId=mahendrapaipuri-dashboardreporter-app status=ok
logger=context userId=1 orgId=1 uname=thrukadmin t=2025-06-20T15:58:09.384414466+07:00 level=error msg="Request Completed" method=GET path=/api/plugins/mahendrapaipuri-dashboardreporter-app/resources/report status=500 remote_addr=10.98.100.192 time_ms=33219 duration=33.219664915s size=24 referer= handler=/api/plugins/:pluginId/resources/* status_source=downstream
logger=rendering renderer=http t=2025-06-20T16:00:35.248312915+07:00 level=debug msg="calling remote rendering service" url=http://renderer:8081/render/version
logger=cleanup t=2025-06-20T16:05:35.27980045+07:00 level=info msg="Completed cleanup jobs" duration=31.074224ms
logger=plugins.update.checker t=2025-06-20T16:05:35.909435772+07:00 level=info msg="Update check succeeded" duration=319.383167ms
```

Please help meee
