### ISSUE TITLE
Multiple Orgs

### ISSUE THREAD

**Issue by 0lIvIa09** [mahendrapaipuri/grafana-dashboard-reporter-app#48]
Hi, does this plugin work with multiple organisations within Grafana, or is only one org supported?

**Comment by mahendrapaipuri** [comment]
It should work with multiple organisations. The plugin shouldn't have any limitations with multi org setup. 

Do you have any issues with multi org setup? If so, please report them here so we can try to fix them.

**Comment by 0lIvIa09** [comment]
I haven't tried it as of yet. Do I just add another block in the reporter.yml file with another org, like so:

```
apps:
  - type: mahendrapaipuri-dashboardreporter-app
    org_id: 32
    org_name: Test
    disabled: false
    org_id: 33
    org_name: Test 2
```

Also I have another question about the logo. It is base64 encoded, but shows up like this on my generated report. Is there anything I'm doing wrong?

![image](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/assets/155996582/780f4a75-f343-40e2-b51d-252ccd009246)

**Comment by mahendrapaipuri** [comment]
Provisioning should be rather like below:

```
apps:
  - type: mahendrapaipuri-dashboardreporter-app
    org_id: 1
    org_name: Main Org.
    disabled: false
    jsonData:
      appUrl: http://localhost:3000

  - type: mahendrapaipuri-dashboardreporter-app
    org_id: 2
    org_name: Main Org.
    disabled: false
     jsonData:
      appUrl: http://localhost:3000
```

About the logo, the encoding should be of a PNG file. If you still have issues, you can enable `Persist Data Files` in plugin config in Grafana UI which will save all the templated HTML files in `$GRAFANA_PATH_DATA/reports/debug` folder and there you can inspect the `footer.html` if logo has been correctly embedded or not.

**Comment by 0lIvIa09** [comment]
I enabled the Persist Data Files, but no footer.html is created only report.html. I am encoding a PNG file and putting its path in the report.yml file like /etc/grafana/provisioning/plugins/logo.

**Comment by mahendrapaipuri** [comment]
Yeah, you are right. There wont be any `footer.html` file. The templated footer will be passed to `chromium` [directly](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/88d0c230b07ce19f896a6960935ca1a55e7cd959/pkg/plugin/report.go#L365) without saving to filesystem.

You will to put the actual encoded string in the `report.yml` file. For example it would be somthing like

```
apps:
  - type: mahendrapaipuri-dashboardreporter-app
    org_id: 1
    org_name: Main Org.
    disabled: false
    jsonData:
      appUrl: http://localhost:3000
      logo: iVBORw0KGgoAAAANSUhEUgAAABcAAAAXCAYAAADgKtSgAAAAAXNSR0IArs4c6QAAAAlwSFlzAAASdAAAEnQB3mYfeAAAABl0RVh0U29mdHdhcmUATWljcm9zb2Z0IE9mZmljZX/tNXEAAAVbSURBVEhLbVVdbFRFFP7mzty9+9N2W4NIqQq2pRSt+OS/IMS/8EAMEtTEYOKLIT7x4oMPZLNBY2LiC09qYngwJhoIiRhDCKIhNIRISEAKpaWlLVBopZXdbXe3vT8zfnO3W37sZCd378zcc77znW/OUfl8HkuN3LjX6KBlo9TO6zDYZIzp4rk0hJgVBgNCiD+1ML+Ho/pkfsNEZSkb6sHFXN+KrGrU25WT2AblrTESWYR+E6IoCWjAOCnjyG7juithzFb1hH/pi5EVh/zy1cP5nnTpXnv3Gd871NyhmtQnJpF6Rxi9GsKhsYiz/ongH7oTyNBwBkK2QibWRjK1Xsk1PV9eLnzzWXd5tH560XhuaFmXTGV2C+V9yJAzCOaBMLDGOK3R+uB75HOP0667CQg30QEnsyuUyssNufvynYURezo2Tn4fUl7qY9Kwk5xmTLWEKAiBgKhdCekqLi/4iX3wpe4vtCDoKNWU5fcfKS9TzvUlv8r3TJRi48rPvm089b4QToOpFInVIEmDTWkPpTBCoO2KuA//3UgWvBAQ0tmscdydiXR0gfs/q9z4uqxyZnbQcBv8CjTRphISm3oexebulei9MoHjf1/DrB9Bcf0u/w9KgXT5VaZJPq5d573c+Eu/KieceYW8dcTJiwIYGm9s8LB5XRs+eLETmYTCX/03MVusIpTJGnpjIwEccuU4dX74tPQkGwHprVPR6HNKOnqLEWiGJr82eE+i6Ic42ncdPinpHbyFAt9phcjCBeA0zZ+2iaBzR/JpvdFpbEeIZv5/U0Gb1xCFdEcNE5c9I4lmjhGMTs2iWAmQTiWwYW0r0jR0404ZK5vTSCqJC+N3MDhZ5OcaUtK5dWaVxNwJIzYpou7kbo1Mu0l0LQ1JbH1mFTbS4LG+G6gEAbY9244NXa2oMppljSkYrXH5ZgGfHz6LU4zOxh07iJFHSVrrsjEp3r672Yk0EkS+5pEmvNCxHFdvl5CictpaMniqrQXnx6bQe+kGXmayt6x/DGfHbuMS1wplSpIRxsMYG0aGtEQkVFjktcwQfUS35fkQFUZR4TPkgqYc7fu+387h4Kkr+PTd57H7rafR/nATskkXBSZ8UatCaBJRVixCQ0aqVYwnVUvq0sPmYZroxqdmUCpVcX16FhEdSoK59/6SCcv5nNDBIGkRxyHVDnpKIaL3GnhQRovTSs4a95hE11MsJxIeZ3ymLsX6DZaWGjNrnPAPFWnniGPwBj0ujyFQTvFV5/CpAjusCgPmwtIVI11Aa/ftzbXOYxnap0Ue+QU40TGlVWOvE8wMI+F1sYiwlviYCTRODNzEXBjGN3SSNJwYuIXR6TLGChUY1pt+KuXgmWGcG5vm+VoNguL3mimM/P7QaT+j8m39xb0jyw8Y464XiXSb9HyUmLiDp4dw9OxI/H+WCH88ORCraHqOlTKZwOmhSQxen0aZhu0Z6ZEOlxL1q9dkgJ/y7acqceEKE8VflE49SfHuEplsQ1guYqpYwZSlhYgEpThZLhMVQ6cyFLmfqTLCAtfIu0NnTibLfV0UOvzB9/QRazc2nm+b/zc3Nv+dDHRGqOROJ9Pc4LjsXPfW87RN1AK3RpMBJsJlc1Je7anDEmvL/nC+/D3r+cyi8djBqokr7ERfwzMV46a2C0ethscPbSeyThZqT+zA5oZ3r3Y9mNQoHBZh5YAqF7/ds1Qnsg72dBaGc32te1XmzkXqjD002UUFZDlZeyhVNlB7tymROa6VaJVog4tSzx/yVfHwnu75GHF9/K9B53v6i9zcz0Z9wMlW2f0pUyFetbXCXmkIU+UFGRB+wO4vFrr/P0t2//8A3e1remyXHJwAAAAASUVORK5CYII=
```

You dont need to include the header `data:image/png;base64` as it will be included automatically by the plugin.

**Comment by 0lIvIa09** [comment]
Thanks the logo appears now. The issue was that I put the path to the base64 encoded file in report.yml instead of just the encoded string. Is there any way I can make the logo any bigger?

**Comment by mahendrapaipuri** [comment]
> Is there any way I can make the logo any bigger?

Unfortunately, no. As placing panel PNGs in the report is always tricky with CSS magic, the logo size is hard coded to the size of footer to avoid distortions.

**Comment by 0lIvIa09** [comment]
Hi, how do I customise the text in the report. What file do I make this change in?

**Comment by mahendrapaipuri** [comment]
Hey, there is no way to customize the report content as of now. There are few features in pipeline that can allow the users to be able to do this.

If I may know your use case, what exactly you would like to change? This helps us to better draft the feature.

**Comment by 0lIvIa09** [comment]
I am looking to add like a cover page to the report with my logo, name, title of the report etc. Also maybe customise the text at the top of every page so that it doesn't show and only the images are on the pages.

**Comment by mahendrapaipuri** [comment]
We will definitely allow the users to customize the header and footer of the report so that you can remove the title from each page. Regarding the cover page, we will look into it if we can support it. If not you can generate the cover page with third party tools and merge it with generated report.

**Comment by Davidkramer1999** [comment]
The issue arises when dealing with multiple organizations. For example, if you have the following organizations:

	1.	Main.org
	2.	Second.org

The issue stems from the service account token. Initially, Grafana sets up the service account for the default organization, which in this case is Main.org. You can verify this by checking the service accounts on the UI. However, when you add another organization, that doesn’t happen automatically.

Now, if you switch to Second.org and attempt to generate a report, you’ll encounter the error: “permission denied”. You can resolve this by manually adding a service account under the second organization and then adding the token in the plugin settings. So, the issue is more of a persistent one.

By checking the repository, I can see that the developer is aware of this problem. Here’s how you can generate a report using Postman by adding the correct Bearer token. This is why they added the following code:

`case conf.Token != "":
	ctxLogger.Debug("using user configured token")
	credential = client.Credential{
		HeaderName:  backend.OAuthIdentityTokenHeaderName,
		HeaderValue: "Bearer " + conf.Token,
	}`
	
You can find this code under pkg -> plugin -> resources.

To understand the issue, you need to grasp how the plugin’s anatomy works. When switching between organizations, the plugin’s backend doesn’t reload. This means the token needs to be correctly managed for each organization. You cannot fetch a dashboard from Second.org while using the token from Main.org. So, adding another service account under Second.org is a permanent solution, but when you reload the container, the token is lost.

Now, someone might suggest adding another token within the plugin’s context. No, the problem arises because when fetching via the HTTP API http://127.0.0.1:3000/api/dashboards/uid/<dashboard_uid>, it doesn’t return the organization to which the dashboard belongs. You already need the correct token to even retrieve that information via the API.



To provision the organization which doesn't work. The response from @mahendrapaipuri :	
	
`apps:
  - type: mahendrapaipuri-dashboardreporter-app
    org_id: 1
    org_name: Main Org.
    disabled: false
    jsonData:
      appUrl: http://localhost:3000

  - type: mahendrapaipuri-dashboardreporter-app
    org_id: 2
    org_name: Second Org.
    disabled: false
    jsonData:
      appUrl: http://localhost:3000 `
      
The only potential solution I can think of is to add the organization in the URL, which could allow us to retrieve the corresponding token. However, this would only be feasible if Grafana generates a separate service account token for each organization.

**Comment by mahendrapaipuri** [comment]
Hey @Davidkramer1999 

Thanks for this detailed report. I confirm all your findings and Grafana developers have acknowledged this issue as well. Please check the [issue](https://github.com/grafana/grafana/issues/91844) in Grafana repo. Until someone fixes that upstream, we can use the following workaround:

Whenever an organisation is created in Grafana, create a service account token "manually" using `Admin` as scope. Then we can use this token in provisioned config for the plugin as follows:

```
# Assuming that externalServiceAccounts feature flag is enabled. Grafana
# will create a token for Main Org. automatically. However, it wont for
# for any additional Orgs. So, we need to create a token with `Admin`
# scope manually and provision it with the plugin.
apps:
  - type: mahendrapaipuri-dashboardreporter-app
    org_id: 1
    org_name: Main Org.
    disabled: false
    jsonData:
      appUrl: http://localhost:3000

  - type: mahendrapaipuri-dashboardreporter-app
    org_id: 2
    org_name: Main Org.
    disabled: false
    secureJsonData:
      saToken: <myscrettoken>
    jsonData:
      appUrl: http://localhost:3000
```

This will ensure that the token survives Grfana reloads/restarts. The inconvenience is that every time we create a new Org., we need to create a token manually and re-provision the plugin. But this has to be done only once.

Please let me know if it works for you.
