### ISSUE TITLE
Plugin not working with Grafana API

### ISSUE THREAD

**Issue by Adrian-LSY** [mahendrapaipuri/grafana-dashboard-reporter-app#77]
Hello, I've been encountering issues generating PDFs using service accounts and the Grafana API. In my Grafana app, I have several orgs. Generating PDFs from the browser is working as intended tho.

I'm currently on Grafana  version `10.3.4`
Plugin version `1.5.0`

At the moment I am trying to generate a pdf from the dashboard `c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6` using the service account `glsa_<token>`
This dashboard is found in the org id `4`
### Here are some details about the service account.
```
curl -H "Authorization: Bearer <token>" -X GET 'http://localhost:3000/api/access-control/user/permissions'
```

```json
{
  "annotations:create": [
    "annotations:type:dashboard"
  ],
  "annotations:delete": [
    "annotations:type:dashboard"
  ],
  "annotations:read": [
    "annotations:*"
  ],
  "annotations:write": [
    "annotations:type:dashboard"
  ],
  "dashboards:read": [
    "dashboards:uid:c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6"
  ],
  "datasources.id:read": [
    "datasources:*"
  ],
  "datasources:query": [
    "datasources:*",
    "datasources:uid:grafana"
  ],
  "datasources:read": [
    "datasources:*",
    "datasources:uid:grafana"
  ],
  "library.panels:read": [
    "folders:uid:general"
  ],
  "orgs.quotas:read": [
    ""
  ],
  "orgs:read": [
    ""
  ],
  "plugins.app:access": [
    "plugins:*"
  ]
}
```

  

### Requesting the endpoint
```
$ curl -o report.pdf -H "Authorization: Bearer <token>" "http://localhost:3000/api/plugins/mahendrapaipuri-dashboardreporter-app/resources/report?dashUid=dashboards:uid:c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6"
```
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

  

                                 Dload  Upload   Total   Spent    Left  Speed

  

100    24    0    24    0     0      5      0 --:--:--  0:00:04 --:--:--     6
```  
```
$ cat report.pdf
```
```
error generating report
```

The API returns: `error generating report`

### Here's logs of when the the request was sent
It seems that the plugin is trying to grab the dashboard from the org id of `1` which returns a 404 and tries to authenticate the account with an org id of 0

```

grafana-instance | logger=plugin.mahendrapaipuri-dashboardreporter-app t=2024-08-12T03:58:20.446670256Z level=debug msg="no variables found" dash_uid=dashboards:uid:c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6 endpoint=callResource pluginID=mahendrapaipuri-dashboardreporter-app user=sa-reporting

grafana-instance | logger=plugin.mahendrapaipuri-dashboardreporter-app t=2024-08-12T03:58:20.446724136Z level=debug msg="time range" endpoint=callResource pluginID=mahendrapaipuri-dashboardreporter-app range="map[From:now-1h To:now]" user=sa-reporting dash_uid=dashboards:uid:c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6

grafana-instance | logger=plugin.mahendrapaipuri-dashboardreporter-app t=2024-08-12T03:58:20.446887003Z level=info msg="updated config" config="Grafana App URL: http://localhost:3000; Skip TLS Check: false; Grafana Data Path: /var/lib/grafana; Orientation: landscape; Layout: grid; Dashboard Mode: full; Time Zone: ; Encoded Logo: ; Max Renderer Workers: 2; Persist Data: false; Included Panel IDs: all; Excluded Panel IDs: none" dash_uid=dashboards:uid:c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6 endpoint=callResource pluginID=mahendrapaipuri-dashboardreporter-app user=sa-reporting

grafana-instance | logger=context userId=43 orgId=1 uname=sa-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-08-12T03:58:20.525016712Z level=error msg="Dashboard not found" error="Dashboard not found" remote_addr=10.0.0.237 traceID=

grafana-instance | logger=context userId=43 orgId=1 uname=sa-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-08-12T03:58:20.525160181Z level=info msg="Request Completed" method=GET path=/api/dashboards/uid/dashboards:uid:c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6 status=404 remote_addr=10.0.0.237 time_ms=66 duration=66.99388ms size=46 referer= handler=/api/dashboards/uid/:uid

grafana-instance | logger=context userId=0 orgId=0 uname= t=2024-08-12T03:58:22.685304399Z level=info msg= error="[auth.unauthorized] cannot authenticate request" remote_addr=10.0.0.237 traceID=

grafana-instance | logger=context userId=0 orgId=0 uname= t=2024-08-12T03:58:22.686641284Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=10.0.0.237 time_ms=1 duration=1.229986ms size=102 referer= handler=/api/live/ws

grafana-instance | logger=context userId=43 orgId=1 uname=sa-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-08-12T03:58:23.318566947Z level=error msg="Dashboard not found" error="Dashboard not found" remote_addr=10.0.0.237 traceID=

grafana-instance | logger=context userId=43 orgId=1 uname=sa-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-08-12T03:58:23.318658928Z level=info msg="Request Completed" method=GET path=/api/dashboards/uid/dashboards:uid:c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6 status=404 remote_addr=10.0.0.237 time_ms=85 duration=85.686314ms size=46 referer=http://localhost:3000/d/dashboards:uid:c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6/_? handler=/api/dashboards/uid/:uid

grafana-instance | logger=context userId=43 orgId=1 uname=sa-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-08-12T03:58:23.41560385Z level=error msg="Dashboard not found" error="Dashboard not found" remote_addr=10.0.0.237 traceID=

grafana-instance | logger=context userId=43 orgId=1 uname=sa-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-08-12T03:58:23.415706886Z level=info msg="Request Completed" method=GET path=/api/dashboards/uid/dashboards:uid:c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6 status=404 remote_addr=10.0.0.237 time_ms=94 duration=94.248505ms size=46 referer=http://localhost:3000/d/dashboards:uid:c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6/_? handler=/api/dashboards/uid/:uid

grafana-instance | logger=context userId=0 orgId=0 uname= t=2024-08-12T03:58:23.718358061Z level=info msg= error="[auth.unauthorized] cannot authenticate request" remote_addr=10.0.0.237 traceID=

grafana-instance | logger=context userId=0 orgId=0 uname= t=2024-08-12T03:58:23.718970707Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=10.0.0.237 time_ms=0 duration=642.174µs size=102 referer= handler=/api/live/ws

grafana-instance | logger=context userId=43 orgId=1 uname=sa-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-08-12T03:58:23.722980148Z level=info msg="Request Completed" method=GET path=/api/user/orgs status=403 remote_addr=10.0.0.237 time_ms=194 duration=194.884201ms size=47 referer="http://localhost:3000/d/dashboards:uid:c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6/_?orgId=1" handler=/api/user/orgs

grafana-instance | logger=context userId=43 orgId=1 uname=sa-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-08-12T03:58:23.823860452Z level=error msg="Invalid dashboard UID in annotation request" error="Dashboard not found" remote_addr=10.0.0.237 traceID=

grafana-instance | logger=context userId=43 orgId=1 uname=sa-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-08-12T03:58:23.824173392Z level=info msg="Request Completed" method=GET path=/api/annotations status=400 remote_addr=10.0.0.237 time_ms=62 duration=62.52623ms size=70 referer="http://localhost:3000/d/dashboards:uid:c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6/_?orgId=1" handler=/api/annotations

grafana-instance | logger=plugin.mahendrapaipuri-dashboardreporter-app t=2024-08-12T03:58:24.455968332Z level=error msg="error generating report" endpoint=callResource err="error fetching dashboard dashboards:uid:c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6: unexpected end of JSON input\nerror obtaining dashboard from http://localhost:3000/api/dashboards/uid/dashboards:uid:c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6. Got Status 404 Not Found, message: {\"message\":\"Dashboard not found\",\"traceID\":\"\"} " pluginID=mahendrapaipuri-dashboardreporter-app

grafana-instance | logger=context userId=45 orgId=4 uname=sa-reporting t=2024-08-12T03:58:24.45658772Z level=error msg="Request Completed" method=GET path=/api/plugins/mahendrapaipuri-dashboardreporter-app/resources/report status=500 remote_addr=10.0.1.166 time_ms=4070 duration=4.070148999s size=24 referer= handler=/api/plugins/:pluginId/resources/*
```

**Comment by mahendrapaipuri** [comment]
Hello,

You will have to pass `orgId=4` query parameter as well. I see that you have `dashboards:uid` prefix before the actual UID of the dashboard. It should not be there. In your case, the request should be `$ curl -o report.pdf -H "Authorization: Bearer <token>" "http://localhost:3000/api/plugins/mahendrapaipuri-dashboardreporter-app/resources/report?dashUid=c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6&orgId=4"`.

PS: Please redact all sensitive info before posting on public forums like GitHub issues.

**Comment by mahendrapaipuri** [comment]
Did you enable the plugin for Org 4? The provisioning should be made for each organization separately. I sense that the plugin is using the service token provisioned for Org 1 to make API requests to the resources on Org 4.

**Comment by Adrian-LSY** [comment]
I believe I enabled the plugin app-wide. How would I make separate provisioning for each organization?

**Comment by mahendrapaipuri** [comment]
Plugin apps are enabled only Org wide. A sample config file can be:

```
apiVersion: 1

apps:
  - type: mahendrapaipuri-dashboardreporter-app
    org_id: 1
    org_name: <Org name>
    disabled: false
    secureJsonData:
       <snippedt>
    jsonData:
       <snippet>

- type: mahendrapaipuri-dashboardreporter-app
    org_id: 4
    org_name: <Org name>
    disabled: false
    secureJsonData:
       <snippedt>
    jsonData:
       <snippet>
```

**Comment by Adrian-LSY** [comment]
Alright, here is my version of the config.
Following the instructions in the readme and the sample config in the repo, here's what I have at the moment

```
apiVersion: 1

apps:
  - type: mahendrapaipuri-dashboardreporter-app
    org_id: 1
    org_name: Main Org.
    disabled: false

  - type: mahendrapaipuri-dashboardreporter-app
    org_id: 4
    org_name: foobar
    disabled: false
    secureJsonData:
      saToken: 'some-token'
```
I've added it to my docker container `/etc/grafana/provisioning/plugins/reporter.yaml`
I've restarted the container and ran the curl command again with the same results.

I'm quite certain I'm missing something here.

**Comment by mahendrapaipuri** [comment]
How did you get `some-token` that you are using in the config?

If you are using `externalServiceAccounts` feature flag, there is no need to pass any token to the plugin. And you need to create token for each org separately. You cannot use token created in Org 1 to make requests to Org 4. Grafana identifies the Org based on the API token you use.

Here should be your workflow:

- Enable `externalServiceAccounts` feature flag in your Grafana instance
- Provision the plugin for both orgs with the config you posted (you can remove `secureJsonData` block tho)
- Switch Org to Org 4 and create a new service account and a token
- Use this token to make API requests to plugin

**Comment by Adrian-LSY** [comment]
Alright i'll try to document the process as best as I can

### Here's the contents of my docker-compose
```
version: '3.0'

services:
  grafana:
    image: custom-grafana-img
    container_name: 'grafana-instance'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-oss}
        grafana_version: ${GRAFANA_VERSION:-10.3.4}
    ports:
      - 3000:${GF_SERVER_HTTP_PORT:-3000}/tcp
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=${GF_FEATURE_TOGGLES_ENABLE:-externalServiceAccounts}
      - GF_ALERTING_ENABLED=false
      - GF_UNIFIED_ALERTING_ENABLED=false
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=https://grafana:${GF_SERVER_HTTP_PORT:-3000}/
      - "GF_LOG_FILTERS=rendering:debug plugin.mahendrapaipuri-dashboardreporter-app:debug"
  renderer:
    image: grafana/grafana-image-renderer:latest
    environment:
      - RENDERING_MODE=clustered
      - RENDERING_CLUSTERING_MODE=browser
      - RENDERING_CLUSTERING_MAX_CONCURRENCY=5
      - RENDERING_CLUSTERING_TIMEOUT=60
      - IGNORE_HTTPS_ERRORS=true
    ports:
      - 8081
  chrome:
    image: chromedp/headless-shell:latest
    shm_size: 2G
    init: true
    network_mode: service:grafana
```

### reporter.yaml
```
apiVersion: 1

apps:
  - type: mahendrapaipuri-dashboardreporter-app
    org_id: 1
    org_name: Main Org.
    disabled: false

  - type: mahendrapaipuri-dashboardreporter-app
    org_id: 4
    org_name: foobar
    disabled: false
```

Here's the workflow I followed:
ran docker-compose down and up
copied the contents of reporter.yaml to /etc/grafana/provisioning/plugins/reporter.yaml

restarted the container to load the provisioning

created a new service account:
<img width="1168" alt="Screenshot 2024-08-12 at 5 57 16 PM" src="https://github.com/user-attachments/assets/7a0e1dbb-588e-44a1-b53c-f17da04b0972">

Got the new token and ran the curl command
```
$   $ curl -o report.pdf -H "Authorization: Bearer <new_token>" "http://localhost:3000/report?dashUid=c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6&orgId=4"
```
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    24    0    24    0     0      6      0 --:--:--  0:00:03 --:--:--     6
```
```
$ cat report.pdf 
```
```
error generating report
```

Here is the log file
I just noticed, the context userId=43 orgId=1 uname=sa-1-extsvc-mahendrapaipuri-dashboardreporter-app is used to look for the dashboard

The response context is userId=50 orgId=4 uname=sa-reporter which I believe is the newly created service account 

```
omni-grafana-prod | logger=plugin.mahendrapaipuri-dashboardreporter-app t=2024-08-12T10:06:53.157682632Z level=debug msg="no variables found" dash_uid=c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6 endpoint=callResource pluginID=mahendrapaipuri-dashboardreporter-app user=sa-reporter
omni-grafana-prod | logger=plugin.mahendrapaipuri-dashboardreporter-app t=2024-08-12T10:06:53.159379911Z level=debug msg="time range" range="map[From:now-1h To:now]" user=sa-reporter dash_uid=c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6 endpoint=callResource pluginID=mahendrapaipuri-dashboardreporter-app
omni-grafana-prod | logger=plugin.mahendrapaipuri-dashboardreporter-app t=2024-08-12T10:06:53.160408028Z level=info msg="updated config" config="Grafana App URL: http://localhost:3000; Skip TLS Check: false; Grafana Data Path: /var/lib/grafana; Orientation: landscape; Layout: grid; Dashboard Mode: full; Time Zone: ; Encoded Logo: ; Max Renderer Workers: 2; Persist Data: false; Included Panel IDs: all; Excluded Panel IDs: none" dash_uid=c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6 endpoint=callResource pluginID=mahendrapaipuri-dashboardreporter-app user=sa-reporter
omni-grafana-prod | logger=context userId=43 orgId=1 uname=sa-1-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-08-12T10:06:53.289254366Z level=error msg="Dashboard not found" error="Dashboard not found" remote_addr=10.0.1.166 traceID=
omni-grafana-prod | logger=context userId=43 orgId=1 uname=sa-1-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-08-12T10:06:53.289351636Z level=info msg="Request Completed" method=GET path=/api/dashboards/uid/c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6 status=404 remote_addr=10.0.1.166 time_ms=106 duration=106.736175ms size=46 referer= handler=/api/dashboards/uid/:uid
omni-grafana-prod | logger=context userId=0 orgId=0 uname= t=2024-08-12T10:06:55.369794652Z level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=10.0.0.237 time_ms=0 duration=114.763µs size=29 referer= handler=/
omni-grafana-prod | logger=context userId=0 orgId=0 uname= t=2024-08-12T10:06:55.770446227Z level=info msg= error="[auth.unauthorized] cannot authenticate request" remote_addr=10.0.1.166 traceID=
omni-grafana-prod | logger=context userId=0 orgId=0 uname= t=2024-08-12T10:06:55.784361414Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=10.0.1.166 time_ms=14 duration=14.068967ms size=102 referer= handler=/api/live/ws
omni-grafana-prod | logger=context userId=43 orgId=1 uname=sa-1-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-08-12T10:06:56.495790043Z level=error msg="Dashboard not found" error="Dashboard not found" remote_addr=10.0.1.166 traceID=
omni-grafana-prod | logger=context userId=43 orgId=1 uname=sa-1-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-08-12T10:06:56.498351104Z level=info msg="Request Completed" method=GET path=/api/dashboards/uid/c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6 status=404 remote_addr=10.0.1.166 time_ms=128 duration=128.047016ms size=46 referer=http://localhost:3000/d/c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6/_? handler=/api/dashboards/uid/:uid
omni-grafana-prod | logger=context userId=43 orgId=1 uname=sa-1-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-08-12T10:06:56.639300346Z level=error msg="Dashboard not found" error="Dashboard not found" remote_addr=10.0.1.166 traceID=
omni-grafana-prod | logger=context userId=43 orgId=1 uname=sa-1-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-08-12T10:06:56.639655636Z level=info msg="Request Completed" method=GET path=/api/dashboards/uid/c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6 status=404 remote_addr=10.0.1.166 time_ms=137 duration=137.018825ms size=46 referer=http://localhost:3000/d/c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6/_? handler=/api/dashboards/uid/:uid
omni-grafana-prod | logger=context userId=0 orgId=0 uname= t=2024-08-12T10:06:56.862237719Z level=info msg= error="[auth.unauthorized] cannot authenticate request" remote_addr=10.0.1.166 traceID=
omni-grafana-prod | logger=context userId=0 orgId=0 uname= t=2024-08-12T10:06:56.86644831Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=10.0.1.166 time_ms=4 duration=4.251835ms size=102 referer= handler=/api/live/ws
omni-grafana-prod | logger=context userId=43 orgId=1 uname=sa-1-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-08-12T10:06:57.004563578Z level=info msg="Request Completed" method=GET path=/api/user/orgs status=403 remote_addr=10.0.1.166 time_ms=301 duration=301.267318ms size=47 referer="http://localhost:3000/d/c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6/_?orgId=1" handler=/api/user/orgs
omni-grafana-prod | logger=context userId=43 orgId=1 uname=sa-1-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-08-12T10:06:57.054825056Z level=error msg="Invalid dashboard UID in annotation request" error="Dashboard not found" remote_addr=10.0.1.166 traceID=
omni-grafana-prod | logger=context userId=43 orgId=1 uname=sa-1-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-08-12T10:06:57.054906647Z level=info msg="Request Completed" method=GET path=/api/annotations status=400 remote_addr=10.0.1.166 time_ms=147 duration=147.820041ms size=70 referer="http://localhost:3000/d/c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6/_?orgId=1" handler=/api/annotations
omni-grafana-prod | logger=context userId=0 orgId=0 uname= t=2024-08-12T10:06:57.517386031Z level=info msg= error="[auth.unauthorized] cannot authenticate request" remote_addr=10.0.1.166 traceID=
omni-grafana-prod | logger=context userId=0 orgId=0 uname= t=2024-08-12T10:06:57.517629356Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=10.0.1.166 time_ms=0 duration=279.409µs size=102 referer= handler=/api/live/ws
omni-grafana-prod | logger=plugin.mahendrapaipuri-dashboardreporter-app t=2024-08-12T10:06:57.738474604Z level=error msg="error generating report" endpoint=callResource err="error fetching dashboard c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6: unexpected end of JSON input\nerror obtaining dashboard from http://localhost:3000/api/dashboards/uid/c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6. Got Status 404 Not Found, message: {\"message\":\"Dashboard not found\",\"traceID\":\"\"} " pluginID=mahendrapaipuri-dashboardreporter-app
omni-grafana-prod | logger=context userId=50 orgId=4 uname=sa-reporter t=2024-08-12T10:06:57.7397879Z level=error msg="Request Completed" method=GET path=/api/plugins/mahendrapaipuri-dashboardreporter-app/resources/report status=500 remote_addr=10.0.0.237 time_ms=4697 duration=4.697234391s size=24 referer= handler=/api/plugins/:pluginId/resources/*
```

**Comment by Adrian-LSY** [comment]
Alright i'll try to document the process as best as I can

### Here's the contents of my docker-compose
```
version: '3.0'

services:
  grafana:
    image: custom-grafana-img
    container_name: 'grafana-instance'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-oss}
        grafana_version: ${GRAFANA_VERSION:-10.3.4}
    ports:
      - 3000:${GF_SERVER_HTTP_PORT:-3000}/tcp
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=${GF_FEATURE_TOGGLES_ENABLE:-externalServiceAccounts}
      - GF_ALERTING_ENABLED=false
      - GF_UNIFIED_ALERTING_ENABLED=false
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=https://grafana:${GF_SERVER_HTTP_PORT:-3000}/
      - "GF_LOG_FILTERS=rendering:debug plugin.mahendrapaipuri-dashboardreporter-app:debug"
  renderer:
    image: grafana/grafana-image-renderer:latest
    environment:
      - RENDERING_MODE=clustered
      - RENDERING_CLUSTERING_MODE=browser
      - RENDERING_CLUSTERING_MAX_CONCURRENCY=5
      - RENDERING_CLUSTERING_TIMEOUT=60
      - IGNORE_HTTPS_ERRORS=true
    ports:
      - 8081
  chrome:
    image: chromedp/headless-shell:latest
    shm_size: 2G
    init: true
    network_mode: service:grafana
```

### reporter.yaml
```
apiVersion: 1

apps:
  - type: mahendrapaipuri-dashboardreporter-app
    org_id: 1
    org_name: Main Org.
    disabled: false

  - type: mahendrapaipuri-dashboardreporter-app
    org_id: 4
    org_name: foobar
    disabled: false
```

Here's the workflow I followed:
ran docker-compose down and up
copied the contents of reporter.yaml to /etc/grafana/provisioning/plugins/reporter.yaml

restarted the container to load the provisioning

created a new service account:
<img width="1168" alt="Screenshot 2024-08-12 at 5 57 16 PM" src="https://github.com/user-attachments/assets/9c8f3818-85bf-4bdb-a77b-e5fbe451bd57">

Got the new token and ran the curl command
```
$   $ curl -o report.pdf -H "Authorization: Bearer <new_token>" "http://localhost:3000/report?dashUid=c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6&orgId=4"
```
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    24    0    24    0     0      6      0 --:--:--  0:00:03 --:--:--     6
```
```
$ cat report.pdf
```
```
error generating report
```

Here is the log file
I just noticed, the context userId=43 orgId=1 uname=sa-1-extsvc-mahendrapaipuri-dashboardreporter-app is used to look for the dashboard

The response context is userId=50 orgId=4 uname=sa-reporter which I believe is the newly created service account

```
grafana-instance | logger=plugin.mahendrapaipuri-dashboardreporter-app t=2024-08-12T10:06:53.157682632Z level=debug msg="no variables found" dash_uid=c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6 endpoint=callResource pluginID=mahendrapaipuri-dashboardreporter-app user=sa-reporter
grafana-instance | logger=plugin.mahendrapaipuri-dashboardreporter-app t=2024-08-12T10:06:53.159379911Z level=debug msg="time range" range="map[From:now-1h To:now]" user=sa-reporter dash_uid=c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6 endpoint=callResource pluginID=mahendrapaipuri-dashboardreporter-app
grafana-instance | logger=plugin.mahendrapaipuri-dashboardreporter-app t=2024-08-12T10:06:53.160408028Z level=info msg="updated config" config="Grafana App URL: http://localhost:3000; Skip TLS Check: false; Grafana Data Path: /var/lib/grafana; Orientation: landscape; Layout: grid; Dashboard Mode: full; Time Zone: ; Encoded Logo: ; Max Renderer Workers: 2; Persist Data: false; Included Panel IDs: all; Excluded Panel IDs: none" dash_uid=c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6 endpoint=callResource pluginID=mahendrapaipuri-dashboardreporter-app user=sa-reporter
grafana-instance | logger=context userId=43 orgId=1 uname=sa-1-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-08-12T10:06:53.289254366Z level=error msg="Dashboard not found" error="Dashboard not found" remote_addr=10.0.1.166 traceID=
grafana-instance | logger=context userId=43 orgId=1 uname=sa-1-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-08-12T10:06:53.289351636Z level=info msg="Request Completed" method=GET path=/api/dashboards/uid/c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6 status=404 remote_addr=10.0.1.166 time_ms=106 duration=106.736175ms size=46 referer= handler=/api/dashboards/uid/:uid
grafana-instance | logger=context userId=0 orgId=0 uname= t=2024-08-12T10:06:55.369794652Z level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=10.0.0.237 time_ms=0 duration=114.763µs size=29 referer= handler=/
grafana-instance | logger=context userId=0 orgId=0 uname= t=2024-08-12T10:06:55.770446227Z level=info msg= error="[auth.unauthorized] cannot authenticate request" remote_addr=10.0.1.166 traceID=
grafana-instance | logger=context userId=0 orgId=0 uname= t=2024-08-12T10:06:55.784361414Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=10.0.1.166 time_ms=14 duration=14.068967ms size=102 referer= handler=/api/live/ws
grafana-instance | logger=context userId=43 orgId=1 uname=sa-1-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-08-12T10:06:56.495790043Z level=error msg="Dashboard not found" error="Dashboard not found" remote_addr=10.0.1.166 traceID=
grafana-instance | logger=context userId=43 orgId=1 uname=sa-1-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-08-12T10:06:56.498351104Z level=info msg="Request Completed" method=GET path=/api/dashboards/uid/c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6 status=404 remote_addr=10.0.1.166 time_ms=128 duration=128.047016ms size=46 referer=http://localhost:3000/d/c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6/_? handler=/api/dashboards/uid/:uid
grafana-instance | logger=context userId=43 orgId=1 uname=sa-1-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-08-12T10:06:56.639300346Z level=error msg="Dashboard not found" error="Dashboard not found" remote_addr=10.0.1.166 traceID=
grafana-instance | logger=context userId=43 orgId=1 uname=sa-1-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-08-12T10:06:56.639655636Z level=info msg="Request Completed" method=GET path=/api/dashboards/uid/c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6 status=404 remote_addr=10.0.1.166 time_ms=137 duration=137.018825ms size=46 referer=http://localhost:3000/d/c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6/_? handler=/api/dashboards/uid/:uid
grafana-instance | logger=context userId=0 orgId=0 uname= t=2024-08-12T10:06:56.862237719Z level=info msg= error="[auth.unauthorized] cannot authenticate request" remote_addr=10.0.1.166 traceID=
grafana-instance | logger=context userId=0 orgId=0 uname= t=2024-08-12T10:06:56.86644831Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=10.0.1.166 time_ms=4 duration=4.251835ms size=102 referer= handler=/api/live/ws
grafana-instance | logger=context userId=43 orgId=1 uname=sa-1-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-08-12T10:06:57.004563578Z level=info msg="Request Completed" method=GET path=/api/user/orgs status=403 remote_addr=10.0.1.166 time_ms=301 duration=301.267318ms size=47 referer="http://localhost:3000/d/c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6/_?orgId=1" handler=/api/user/orgs
grafana-instance | logger=context userId=43 orgId=1 uname=sa-1-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-08-12T10:06:57.054825056Z level=error msg="Invalid dashboard UID in annotation request" error="Dashboard not found" remote_addr=10.0.1.166 traceID=
grafana-instance | logger=context userId=43 orgId=1 uname=sa-1-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-08-12T10:06:57.054906647Z level=info msg="Request Completed" method=GET path=/api/annotations status=400 remote_addr=10.0.1.166 time_ms=147 duration=147.820041ms size=70 referer="http://localhost:3000/d/c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6/_?orgId=1" handler=/api/annotations
grafana-instance | logger=context userId=0 orgId=0 uname= t=2024-08-12T10:06:57.517386031Z level=info msg= error="[auth.unauthorized] cannot authenticate request" remote_addr=10.0.1.166 traceID=
grafana-instance | logger=context userId=0 orgId=0 uname= t=2024-08-12T10:06:57.517629356Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=10.0.1.166 time_ms=0 duration=279.409µs size=102 referer= handler=/api/live/ws
grafana-instance | logger=plugin.mahendrapaipuri-dashboardreporter-app t=2024-08-12T10:06:57.738474604Z level=error msg="error generating report" endpoint=callResource err="error fetching dashboard c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6: unexpected end of JSON input\nerror obtaining dashboard from http://localhost:3000/api/dashboards/uid/c1bd0ad3-cd1b-46a5-b29f-6d33233c6ff6. Got Status 404 Not Found, message: {\"message\":\"Dashboard not found\",\"traceID\":\"\"} " pluginID=mahendrapaipuri-dashboardreporter-app
grafana-instance | logger=context userId=50 orgId=4 uname=sa-reporter t=2024-08-12T10:06:57.7397879Z level=error msg="Request Completed" method=GET path=/api/plugins/mahendrapaipuri-dashboardreporter-app/resources/report status=500 remote_addr=10.0.0.237 time_ms=4697 duration=4.697234391s size=24 referer= handler=/api/plugins/:pluginId/resources/*
```
